spring:
  application:
    name: github-code-scanner
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN:}
    timeout: 30
    max-retry-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.github.scanner: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"